const SET_NETWORK_NAME = '[SET_NETWORK_NAME]';
const SET_SMART_CONTRACT_NAME = '[SET_SMART_CONTRACT_NAME]';
const SET_NONCE = '[SET_NONCE]';
const SET_FROM = '[SET_FROM]';
const SET_TO = '[SET_TO]';
const SET_AMOUNT = '[SET_AMOUNT]';
const SET_GAS_PRICE = '[SET_GAS_PRICE]';
const SET_GAS_LIMIT = '[SET_GAS_LIMIT]';

const SET_TRANSACTION_RESULT = '[MAKE_TRANSACTION_RESULT]';
const OPEN_TRANSACTION_RESULT_DIALOG = '[OPEN_TRANSACTION_RESULT_DIALOG]';

const SELECT_COIN = 'SELECT_COIN';

export {
	SET_NETWORK_NAME,
	SET_SMART_CONTRACT_NAME,
	SET_NONCE,
	SET_FROM,
	SET_TO,
	SET_AMOUNT,
	SET_GAS_PRICE,
	SET_GAS_LIMIT,
	SET_TRANSACTION_RESULT,
	OPEN_TRANSACTION_RESULT_DIALOG,
	SELECT_COIN
};